package com.kolonial.product.scraper.utils;

public class ProductHTMLExampleUtil {
  public static String productExample =
      "<div class=\"content-wrapper\">\n"
          + "\n"
          + "            \n"
          + "\n"
          + "            \n"
          + "\n"
          + "            \n"
          + "\n"
          + "            \n"
          + "            <div id=\"cart-sidebar\">\n"
          + "                \n"
          + "                    <div class=\"empty-cart product-items\" data-list=\"cart\" data-list-mode=\"grouped\">\n"
          + "\n"
          + "    <div class=\"shadow\"></div>\n"
          + "\n"
          + "    <div class=\"header\">\n"
          + "        <h3>\n"
          + "            Du har ingen varer i handlekurven\n"
          + "        </h3>\n"
          + "    </div>\n"
          + "\n"
          + "    \n"
          + "        <p style=\"padding-top: 250px;\">\n"
          + "            Trenger du hjelp til å komme i gang?<br>\n"
          + "            <a href=\"/introduksjon/\">\n"
          + "                Slik handler du på Kolonial.no\n"
          + "            </a>\n"
          + "        </p>\n"
          + "    \n"
          + "\n"
          + "</div>\n"
          + "\n"
          + "                \n"
          + "            </div>\n"
          + "\n"
          + "            <div id=\"content\">\n"
          + "                \n"
          + "                    <div class=\"wide-container\">\n"
          + "                        <div class=\"content-container\" role=\"main\">\n"
          + "                            \n"
          + "\n"
          + "    <div class=\"row\">\n"
          + "        <div class=\"col-xs-12 col-sm-3 hidden-in-webview\">\n"
          + "            \n"
          + "\n"
          + "\n"
          + "<div class=\"filter-sidebar\">\n"
          + "    <nav class=\"navbar navbar-default\">\n"
          + "\n"
          + "        <div class=\"navbar-toggle visible-xs-block\" data-toggle=\"collapse\" data-target=\"#navbar-category-sidebar\">\n"
          + "            <h3 class=\"category-sidebar\">\n"
          + "                \n"
          + "                    Kategorier\n"
          + "                \n"
          + "            </h3>\n"
          + "            <span class=\"sr-only\">Vis/skjul kategorier</span>\n"
          + "            <span class=\"glyphicon glyphicon-menu-down\"></span>\n"
          + "        </div>\n"
          + "\n"
          + "        <div class=\"aggregation-filter categories\">\n"
          + "\n"
          + "            <h3 class=\"hidden-xs aggregation-filter-headline all-categories-headline category-sidebar\">\n"
          + "                <a href=\"/kategorier/\">\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                    Alle kategorier\n"
          + "                </a>\n"
          + "            </h3>\n"
          + "\n"
          + "            <div class=\"collapse navbar-collapse\" id=\"navbar-category-sidebar\">\n"
          + "                <ul class=\"list-unstyled\">\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                    <li class=\"parent-category \">\n"
          + "                        <h4 class=\"aggregation-filter-headline\">\n"
          + "                            <a href=\"/produkter/salg/\">\n"
          + "                                På tilbud\n"
          + "                            </a>\n"
          + "                        </h4>\n"
          + "                    </li>\n"
          + "\n"
          + "                    <li class=\"parent-category \">\n"
          + "                        <h4 class=\"aggregation-filter-headline\">\n"
          + "                            <a href=\"/produkter/nyheter/\">\n"
          + "                                Nyheter i butikken\n"
          + "                            </a>\n"
          + "                        </h4>\n"
          + "                    </li>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category  ws-xs\">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/20-frukt-og-gront/\">\n"
          + "                                        Frukt og grønt\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/205-jul/\">\n"
          + "                                        Jul\n"
          + "                                        \n"
          + "                                            <span class=\"product-category-label label label-success\">Ny!</span>\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/488-mathall/\">\n"
          + "                                        Mathall\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/462-clas-ohlson/\">\n"
          + "                                        Clas Ohlson-butikken\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/504-iceland/\">\n"
          + "                                        Iceland\n"
          + "                                        \n"
          + "                                            <span class=\"product-category-label label label-success\">Ny!</span>\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/401-blomster-og-planter/\">\n"
          + "                                        Blomster og planter\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/1-brod-og-frokostblandinger/\">\n"
          + "                                        Brød og frokostblandinger\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/48-melk-meieriprodukter-og-egg/\">\n"
          + "                                        Melk, meieriprodukter og egg\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/26-kjott-og-kylling/\">\n"
          + "                                        Kjøtt og kylling\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/283-fisk-og-sjomat/\">\n"
          + "                                        Fisk og sjømat\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/142-oster/\">\n"
          + "                                        Oster\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/241-serveringsklare-retter/\">\n"
          + "                                        Serveringsklare retter\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/42-palegg/\">\n"
          + "                                        Pålegg\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/32-middager-og-tilbehor/\">\n"
          + "                                        Middager og tilbehør\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/424-pizza-og-taco/\">\n"
          + "                                        Pizza og taco\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/448-asiatisk/\">\n"
          + "                                        Asiatisk\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/60-drikkevarer/\">\n"
          + "                                        Drikkevarer\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/457-varme-drikker/\">\n"
          + "                                        Varme drikker\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/37-olje-og-krydder/\">\n"
          + "                                        Olje og krydder\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/15-mel-og-bakeingredienser/\">\n"
          + "                                        Mel og bakeingredienser\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/408-og-desserter/\">\n"
          + "                                        Is og desserter\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/348-kaker-kjeks-og-desserter/\">\n"
          + "                                        Kaker, kjeks og desserter\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/67-snacks-og-godteri/\">\n"
          + "                                        Snacks og godteri\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/73-barneprodukter/\">\n"
          + "                                        Barneprodukter\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/79-shampo-sape-og-hudpleie/\">\n"
          + "                                        Shampo, såpe og hudpleie\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/435-sminke-og-skjonnhet/\">\n"
          + "                                        Sminke og skjønnhet\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/373-hygieneartikler/\">\n"
          + "                                        Hygieneartikler\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/365-legemidler-og-helsekost/\">\n"
          + "                                        Legemidler og helsekost\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/394-trening/\">\n"
          + "                                        Trening\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/163-torkepapir-og-vaskemidler/\">\n"
          + "                                        Tørkepapir og vaskemidler\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/331-magasiner-og-boker/\">\n"
          + "                                        Magasiner og bøker\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/444-undertoy-og-stromper/\">\n"
          + "                                        Undertøy og strømper\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/85-hus-og-hjem/\">\n"
          + "                                        Hus og hjem\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                            <li class=\"parent-category \">\n"
          + "                                <h4 class=\"aggregation-filter-headline\">\n"
          + "                                    <a href=\"/kategorier/128-dyremat/\">\n"
          + "                                        Dyremat\n"
          + "                                        \n"
          + "                                    </a>\n"
          + "                                </h4>\n"
          + "                            </li>\n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                </ul>\n"
          + "\n"
          + "            </div>\n"
          + "\n"
          + "        </div>\n"
          + "\n"
          + "    </nav>\n"
          + "</div>\n"
          + "\n"
          + "<div class=\"visible-xs-block\">\n"
          + "    \n"
          + "\n"
          + "<ul class=\"nav nav-pills\">\n"
          + "    \n"
          + "        \n"
          + "    \n"
          + "</ul>\n"
          + "\n"
          + "</div>\n"
          + "\n"
          + "        </div>\n"
          + "\n"
          + "        <div class=\"col-xs-12 col-sm-9\">\n"
          + "            <div class=\"product-category-header hidden-in-webview\">\n"
          + "\n"
          + "                <ol class=\"breadcrumb hidden-xs\" itemprop=\"breadcrumb\">\n"
          + "                    <li>\n"
          + "                        <a href=\"/kategorier/\">Alle varer</a>\n"
          + "                    </li>\n"
          + "\n"
          + "                    <li class=\"active\">\n"
          + "                        Tilbudsvarer\n"
          + "                    </li>\n"
          + "                </ol>\n"
          + "\n"
          + "                <h3>\n"
          + "                    Tilbudsvarer\n"
          + "                </h3>\n"
          + "\n"
          + "                <hr>\n"
          + "\n"
          + "                \n"
          + "                    <p class=\"lead light\">\n"
          + "                        Tilbudene gjelder så langt beholdningen rekker. Husk at salgsvarer kan ha kort holdbarhet!\n"
          + "                    </p>\n"
          + "                \n"
          + "            </div>\n"
          + "\n"
          + "\n"
          + "            \n"
          + "            \n"
          + "\n"
          + "            \n"
          + "            \n"
          + "\n"
          + "            \n"
          + "            \n"
          + "\n"
          + "            \n"
          + "            \n"
          + "                <h4 id=\"single-products\" class=\"child-category-headline\">\n"
          + "                    Andre tilbud\n"
          + "                </h4>\n"
          + "\n"
          + "                <div class=\"product-category-list\">\n"
          + "                    <div class=\"row\">\n"
          + "                        \n"
          + "                            \n"
          + "                                \n"
          + "\n"
          + "\n"
          + "    <div class=\"col-xs-6 col-sm-3 col-md-2\">\n"
          + "        <div class=\"product-list-item \">\n"
          + "\n"
          + "                \n"
          + "\n"
          + "\n"
          + "                \n"
          + "                \n"
          + "\n"
          + "    \n"
          + "    \n"
          + "\n"
          + "        <div class=\"discount-bubble\">\n"
          + "            <p>\n"
          + "                \n"
          + "\n"
          + "                \n"
          + "                    -30%\n"
          + "                \n"
          + "            </p>\n"
          + "        </div>\n"
          + "\n"
          + "    \n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "                \n"
          + "                    <a data-app-open-native=\"\" href=\"/produkter/31690-ansiktsmaske-kn95-egenbeskyttelse-4-lag/\" class=\"modal-link\">\n"
          + "                \n"
          + "\n"
          + "                    <div>\n"
          + "                        <div class=\"image-container\">\n"
          + "                            \n"
          + "                                <img src=\"https://bilder.kolonial.no/produkter/9f7c3959-3562-4a45-b80a-28e8154a9756.PNG?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=cb7ff00af49da91cf14f466fe1c6a1ab\" alt=\"Ansiktsmaske KN95\" width=\"140\" height=\"140\" srcset=\"https://bilder.kolonial.no/produkter/9f7c3959-3562-4a45-b80a-28e8154a9756.PNG?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=cb7ff00af49da91cf14f466fe1c6a1ab 1x, https://bilder.kolonial.no/produkter/9f7c3959-3562-4a45-b80a-28e8154a9756.PNG?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=280&amp;w=280&amp;s=32370ba1ac348a6b076d0d8800a1bd4c 2x\">\n"
          + "                            \n"
          + "\n"
          + "                            \n"
          + "                            \n"
          + "\n"
          + "                            <div class=\"product-classifiers\">\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "                                    \n"
          + "                                \n"
          + "\n"
          + "                            </div>\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "\n"
          + "                    <p class=\"price label label-price-discounted\">\n"
          + "                        <span class=\"undiscounted-price\">320,00</span> kr 224,00\n"
          + "                    </p>\n"
          + "\n"
          + "                    \n"
          + "                        <p class=\"unit-price\">\n"
          + "                            kr 22,40 per stk\n"
          + "                        </p>\n"
          + "                    \n"
          + "\n"
          + "                    <h3 class=\"name\">\n"
          + "                        <div class=\"name-main wrap-two-lines\">Ansiktsmaske KN95</div>\n"
          + "                        <div class=\"name-extra wrap-one-line\">\n"
          + "                            \n"
          + "\n"
          + "                            Egenbeskyttelse, 4 lag, 10 stk\n"
          + "                        </div>\n"
          + "                    </h3>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                \n"
          + "                    </a>\n"
          + "                \n"
          + "\n"
          + "                <div class=\"buttons\">\n"
          + "\n"
          + "                    \n"
          + "                        \n"
          + "                            <div class=\"add-to-cart-group\" data-product=\"31690\">\n"
          + "                                <div class=\"not-in-cart\">\n"
          + "                                    <button type=\"button\" class=\" add-to-cart btn btn-sm btn-primary\" data-action=\"add-to-cart\" data-product=\"31690\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Kjøp Ansiktsmaske KN95 Egenbeskyttelse, 4 lag, 10 stk\" data-tr-location=\"Product Discounts\">\n"
          + "                                        Kjøp\n"
          + "                                    </button>\n"
          + "                                </div>\n"
          + "                                <div class=\"in-cart\">\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-1\" data-action=\"add-to-cart\" data-product=\"31690\" data-quantity=\"-1\" data-to-list=\"cart\" aria-label=\"Fjern 1 Ansiktsmaske KN95 fra handlekurven\" title=\"Fjern 1 Ansiktsmaske KN95 fra handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-minus\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Minus-symbol\">\n"
          + "    <rect class=\"fill\" x=\"0\" y=\"19.6\" width=\"45\" height=\"5.8\"></rect>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-3\" data-action=\"add-to-cart\" data-product=\"31690\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Legg til 1 Ansiktsmaske KN95 i handlekurven\" title=\"Legg til 1 Ansiktsmaske KN95 i handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-plus\" x=\"0\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Pluss-symbol\">\n"
          + "    <polygon class=\"fill\" points=\"45 19.6 25.4 19.6 25.4 0 19.6 0 19.6 19.6 0 19.6 0 25.4 19.6 25.4 19.6 45 25.4 45 25.4 25.4 45 25.4 \"></polygon>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <div class=\"cart-quantity position-2\" title=\"Antall i handlekurven\">\n"
          + "                                        \n"
          + "                                    </div>\n"
          + "                                </div>\n"
          + "                            </div>\n"
          + "                        \n"
          + "                    \n"
          + "\n"
          + "                </div>\n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                            \n"
          + "                                \n"
          + "\n"
          + "\n"
          + "    <div class=\"col-xs-6 col-sm-3 col-md-2\">\n"
          + "        <div class=\"product-list-item \">\n"
          + "\n"
          + "                \n"
          + "\n"
          + "\n"
          + "                \n"
          + "                \n"
          + "\n"
          + "    \n"
          + "    \n"
          + "\n"
          + "        <div class=\"discount-bubble\">\n"
          + "            <p>\n"
          + "                \n"
          + "\n"
          + "                \n"
          + "                    -30%\n"
          + "                \n"
          + "            </p>\n"
          + "        </div>\n"
          + "\n"
          + "    \n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "                \n"
          + "                    <a data-app-open-native=\"\" href=\"/produkter/30484-twinings-blackcurrant-blueberry-infuso/\" class=\"modal-link\">\n"
          + "                \n"
          + "\n"
          + "                    <div>\n"
          + "                        <div class=\"image-container\">\n"
          + "                            \n"
          + "                                <img src=\"https://bilder.kolonial.no/produkter/cb078534-b0c7-4181-ab23-e00f58bdd8f7.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=e80b3252912b38033a3c3e39e429924a\" alt=\"Blackcurrant &amp; Blueberry\" width=\"140\" height=\"140\" title=\"Bilde: © Twinings / Kolonial.no\" srcset=\"https://bilder.kolonial.no/produkter/cb078534-b0c7-4181-ab23-e00f58bdd8f7.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=e80b3252912b38033a3c3e39e429924a 1x, https://bilder.kolonial.no/produkter/cb078534-b0c7-4181-ab23-e00f58bdd8f7.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=280&amp;w=280&amp;s=1b2d44e6ef7a59006a2e945f22294dee 2x\">\n"
          + "                            \n"
          + "\n"
          + "                            \n"
          + "                            \n"
          + "\n"
          + "                            <div class=\"product-classifiers\">\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "                                    \n"
          + "                                \n"
          + "\n"
          + "                            </div>\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "\n"
          + "                    <p class=\"price label label-price-discounted\">\n"
          + "                        <span class=\"undiscounted-price\">67,80</span> kr 47,46\n"
          + "                    </p>\n"
          + "\n"
          + "                    \n"
          + "                        <p class=\"unit-price\">\n"
          + "                            kr 2,37 per stk\n"
          + "                        </p>\n"
          + "                    \n"
          + "\n"
          + "                    <h3 class=\"name\">\n"
          + "                        <div class=\"name-main wrap-two-lines\">Blackcurrant &amp; Blueberry</div>\n"
          + "                        <div class=\"name-extra wrap-one-line\">\n"
          + "                            \n"
          + "\n"
          + "                            Infuso, 20 stk\n"
          + "                        </div>\n"
          + "                    </h3>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                \n"
          + "                    </a>\n"
          + "                \n"
          + "\n"
          + "                <div class=\"buttons\">\n"
          + "\n"
          + "                    \n"
          + "                        \n"
          + "                            <div class=\"add-to-cart-group\" data-product=\"30484\">\n"
          + "                                <div class=\"not-in-cart\">\n"
          + "                                    <button type=\"button\" class=\" add-to-cart btn btn-sm btn-primary\" data-action=\"add-to-cart\" data-product=\"30484\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Kjøp Blackcurrant &amp; Blueberry Infuso, 20 stk\" data-tr-location=\"Product Discounts\">\n"
          + "                                        Kjøp\n"
          + "                                    </button>\n"
          + "                                </div>\n"
          + "                                <div class=\"in-cart\">\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-1\" data-action=\"add-to-cart\" data-product=\"30484\" data-quantity=\"-1\" data-to-list=\"cart\" aria-label=\"Fjern 1 Blackcurrant &amp; Blueberry fra handlekurven\" title=\"Fjern 1 Blackcurrant &amp; Blueberry fra handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-minus\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Minus-symbol\">\n"
          + "    <rect class=\"fill\" x=\"0\" y=\"19.6\" width=\"45\" height=\"5.8\"></rect>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-3\" data-action=\"add-to-cart\" data-product=\"30484\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Legg til 1 Blackcurrant &amp; Blueberry i handlekurven\" title=\"Legg til 1 Blackcurrant &amp; Blueberry i handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-plus\" x=\"0\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Pluss-symbol\">\n"
          + "    <polygon class=\"fill\" points=\"45 19.6 25.4 19.6 25.4 0 19.6 0 19.6 19.6 0 19.6 0 25.4 19.6 25.4 19.6 45 25.4 45 25.4 25.4 45 25.4 \"></polygon>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <div class=\"cart-quantity position-2\" title=\"Antall i handlekurven\">\n"
          + "                                        \n"
          + "                                    </div>\n"
          + "                                </div>\n"
          + "                            </div>\n"
          + "                        \n"
          + "                    \n"
          + "\n"
          + "                </div>\n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                            \n"
          + "                                \n"
          + "\n"
          + "\n"
          + "    <div class=\"col-xs-6 col-sm-3 col-md-2\">\n"
          + "        <div class=\"product-list-item \">\n"
          + "\n"
          + "                \n"
          + "\n"
          + "\n"
          + "                \n"
          + "                \n"
          + "\n"
          + "    \n"
          + "    \n"
          + "\n"
          + "        <div class=\"discount-bubble\">\n"
          + "            <p>\n"
          + "                \n"
          + "\n"
          + "                \n"
          + "                    -30%\n"
          + "                \n"
          + "            </p>\n"
          + "        </div>\n"
          + "\n"
          + "    \n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "                \n"
          + "                    <a data-app-open-native=\"\" href=\"/produkter/30483-twinings-ginger-mango-moringa-infuso/\" class=\"modal-link\">\n"
          + "                \n"
          + "\n"
          + "                    <div>\n"
          + "                        <div class=\"image-container\">\n"
          + "                            \n"
          + "                                <img src=\"https://bilder.kolonial.no/produkter/e949125d-1eab-4b92-972f-86df39bbdefc.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=c72bbea430cbb1bcd86a36ad7c550a61\" alt=\"Ginger, Mango &amp; Moringa\" width=\"140\" height=\"140\" title=\"Bilde: © Twinings / Kolonial.no\" srcset=\"https://bilder.kolonial.no/produkter/e949125d-1eab-4b92-972f-86df39bbdefc.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=c72bbea430cbb1bcd86a36ad7c550a61 1x, https://bilder.kolonial.no/produkter/e949125d-1eab-4b92-972f-86df39bbdefc.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=280&amp;w=280&amp;s=f2af76a6a14a475f4c983377c502a11c 2x\">\n"
          + "                            \n"
          + "\n"
          + "                            \n"
          + "                            \n"
          + "\n"
          + "                            <div class=\"product-classifiers\">\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "                                    \n"
          + "                                \n"
          + "\n"
          + "                            </div>\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "\n"
          + "                    <p class=\"price label label-price-discounted\">\n"
          + "                        <span class=\"undiscounted-price\">67,80</span> kr 47,46\n"
          + "                    </p>\n"
          + "\n"
          + "                    \n"
          + "                        <p class=\"unit-price\">\n"
          + "                            kr 2,37 per stk\n"
          + "                        </p>\n"
          + "                    \n"
          + "\n"
          + "                    <h3 class=\"name\">\n"
          + "                        <div class=\"name-main wrap-two-lines\">Ginger, Mango &amp; Moringa</div>\n"
          + "                        <div class=\"name-extra wrap-one-line\">\n"
          + "                            \n"
          + "\n"
          + "                            Infuso, 20 stk\n"
          + "                        </div>\n"
          + "                    </h3>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                \n"
          + "                    </a>\n"
          + "                \n"
          + "\n"
          + "                <div class=\"buttons\">\n"
          + "\n"
          + "                    \n"
          + "                        \n"
          + "                            <div class=\"add-to-cart-group\" data-product=\"30483\">\n"
          + "                                <div class=\"not-in-cart\">\n"
          + "                                    <button type=\"button\" class=\" add-to-cart btn btn-sm btn-primary\" data-action=\"add-to-cart\" data-product=\"30483\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Kjøp Ginger, Mango &amp; Moringa Infuso, 20 stk\" data-tr-location=\"Product Discounts\">\n"
          + "                                        Kjøp\n"
          + "                                    </button>\n"
          + "                                </div>\n"
          + "                                <div class=\"in-cart\">\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-1\" data-action=\"add-to-cart\" data-product=\"30483\" data-quantity=\"-1\" data-to-list=\"cart\" aria-label=\"Fjern 1 Ginger, Mango &amp; Moringa fra handlekurven\" title=\"Fjern 1 Ginger, Mango &amp; Moringa fra handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-minus\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Minus-symbol\">\n"
          + "    <rect class=\"fill\" x=\"0\" y=\"19.6\" width=\"45\" height=\"5.8\"></rect>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-3\" data-action=\"add-to-cart\" data-product=\"30483\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Legg til 1 Ginger, Mango &amp; Moringa i handlekurven\" title=\"Legg til 1 Ginger, Mango &amp; Moringa i handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-plus\" x=\"0\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Pluss-symbol\">\n"
          + "    <polygon class=\"fill\" points=\"45 19.6 25.4 19.6 25.4 0 19.6 0 19.6 19.6 0 19.6 0 25.4 19.6 25.4 19.6 45 25.4 45 25.4 25.4 45 25.4 \"></polygon>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <div class=\"cart-quantity position-2\" title=\"Antall i handlekurven\">\n"
          + "                                        \n"
          + "                                    </div>\n"
          + "                                </div>\n"
          + "                            </div>\n"
          + "                        \n"
          + "                    \n"
          + "\n"
          + "                </div>\n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                            \n"
          + "                                \n"
          + "\n"
          + "\n"
          + "    <div class=\"col-xs-6 col-sm-3 col-md-2\">\n"
          + "        <div class=\"product-list-item \">\n"
          + "\n"
          + "                \n"
          + "\n"
          + "\n"
          + "                \n"
          + "                \n"
          + "\n"
          + "    \n"
          + "    \n"
          + "\n"
          + "        <div class=\"discount-bubble\">\n"
          + "            <p>\n"
          + "                \n"
          + "\n"
          + "                \n"
          + "                    -30%\n"
          + "                \n"
          + "            </p>\n"
          + "        </div>\n"
          + "\n"
          + "    \n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "                \n"
          + "                    <a data-app-open-native=\"\" href=\"/produkter/28784-twinings-infuso-collection/\" class=\"modal-link\">\n"
          + "                \n"
          + "\n"
          + "                    <div>\n"
          + "                        <div class=\"image-container\">\n"
          + "                            \n"
          + "                                <img src=\"https://bilder.kolonial.no/produkter/f2bdceae-df4c-441a-8159-640b810f3340.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=eba4a1d1b59f07dc878b5a00a97a4079\" alt=\"Infuso Collection\" width=\"140\" height=\"140\" title=\"Bilde: © Twinings / Kolonial.no\" srcset=\"https://bilder.kolonial.no/produkter/f2bdceae-df4c-441a-8159-640b810f3340.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=eba4a1d1b59f07dc878b5a00a97a4079 1x, https://bilder.kolonial.no/produkter/f2bdceae-df4c-441a-8159-640b810f3340.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=280&amp;w=280&amp;s=90682e7f7ad5be64c23898e805f4e318 2x\">\n"
          + "                            \n"
          + "\n"
          + "                            \n"
          + "                            \n"
          + "\n"
          + "                            <div class=\"product-classifiers\">\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "                                    \n"
          + "                                \n"
          + "\n"
          + "                            </div>\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "\n"
          + "                    <p class=\"price label label-price-discounted\">\n"
          + "                        <span class=\"undiscounted-price\">86,90</span> kr 60,83\n"
          + "                    </p>\n"
          + "\n"
          + "                    \n"
          + "                        <p class=\"unit-price\">\n"
          + "                            kr 3,04 per stk\n"
          + "                        </p>\n"
          + "                    \n"
          + "\n"
          + "                    <h3 class=\"name\">\n"
          + "                        <div class=\"name-main wrap-two-lines\">Infuso Collection</div>\n"
          + "                        <div class=\"name-extra wrap-one-line\">\n"
          + "                            \n"
          + "\n"
          + "                            20 stk\n"
          + "                        </div>\n"
          + "                    </h3>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                \n"
          + "                    </a>\n"
          + "                \n"
          + "\n"
          + "                <div class=\"buttons\">\n"
          + "\n"
          + "                    \n"
          + "                        \n"
          + "                            <div class=\"add-to-cart-group\" data-product=\"28784\">\n"
          + "                                <div class=\"not-in-cart\">\n"
          + "                                    <button type=\"button\" class=\" add-to-cart btn btn-sm btn-primary\" data-action=\"add-to-cart\" data-product=\"28784\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Kjøp Infuso Collection 20 stk\" data-tr-location=\"Product Discounts\">\n"
          + "                                        Kjøp\n"
          + "                                    </button>\n"
          + "                                </div>\n"
          + "                                <div class=\"in-cart\">\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-1\" data-action=\"add-to-cart\" data-product=\"28784\" data-quantity=\"-1\" data-to-list=\"cart\" aria-label=\"Fjern 1 Infuso Collection fra handlekurven\" title=\"Fjern 1 Infuso Collection fra handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-minus\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Minus-symbol\">\n"
          + "    <rect class=\"fill\" x=\"0\" y=\"19.6\" width=\"45\" height=\"5.8\"></rect>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-3\" data-action=\"add-to-cart\" data-product=\"28784\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Legg til 1 Infuso Collection i handlekurven\" title=\"Legg til 1 Infuso Collection i handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-plus\" x=\"0\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Pluss-symbol\">\n"
          + "    <polygon class=\"fill\" points=\"45 19.6 25.4 19.6 25.4 0 19.6 0 19.6 19.6 0 19.6 0 25.4 19.6 25.4 19.6 45 25.4 45 25.4 25.4 45 25.4 \"></polygon>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <div class=\"cart-quantity position-2\" title=\"Antall i handlekurven\">\n"
          + "                                        \n"
          + "                                    </div>\n"
          + "                                </div>\n"
          + "                            </div>\n"
          + "                        \n"
          + "                    \n"
          + "\n"
          + "                </div>\n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                            \n"
          + "                                \n"
          + "\n"
          + "\n"
          + "    <div class=\"col-xs-6 col-sm-3 col-md-2\">\n"
          + "        <div class=\"product-list-item \">\n"
          + "\n"
          + "                \n"
          + "\n"
          + "\n"
          + "                \n"
          + "                \n"
          + "\n"
          + "    \n"
          + "    \n"
          + "\n"
          + "        <div class=\"discount-bubble\">\n"
          + "            <p>\n"
          + "                \n"
          + "\n"
          + "                \n"
          + "                    -30%\n"
          + "                \n"
          + "            </p>\n"
          + "        </div>\n"
          + "\n"
          + "    \n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "                \n"
          + "                    <a data-app-open-native=\"\" href=\"/produkter/27410-twinings-raspberry-pomegranat-te-infuso/\" class=\"modal-link\">\n"
          + "                \n"
          + "\n"
          + "                    <div>\n"
          + "                        <div class=\"image-container\">\n"
          + "                            \n"
          + "                                <img src=\"https://bilder.kolonial.no/produkter/ba690028-6b87-4142-9f2b-2c8d12554a6e.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=05d78624ea809195ed146b4efb45fbdb\" alt=\"Raspberry &amp; Pomegranat-te\" width=\"140\" height=\"140\" title=\"Bilde: © Twinings / Kolonial.no\" srcset=\"https://bilder.kolonial.no/produkter/ba690028-6b87-4142-9f2b-2c8d12554a6e.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=05d78624ea809195ed146b4efb45fbdb 1x, https://bilder.kolonial.no/produkter/ba690028-6b87-4142-9f2b-2c8d12554a6e.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=280&amp;w=280&amp;s=ae9afff7b716db7454a9cd70db6c0013 2x\">\n"
          + "                            \n"
          + "\n"
          + "                            \n"
          + "                            \n"
          + "\n"
          + "                            <div class=\"product-classifiers\">\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "                                    \n"
          + "                                \n"
          + "\n"
          + "                            </div>\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "\n"
          + "                    <p class=\"price label label-price-discounted\">\n"
          + "                        <span class=\"undiscounted-price\">66,80</span> kr 46,76\n"
          + "                    </p>\n"
          + "\n"
          + "                    \n"
          + "                        <p class=\"unit-price\">\n"
          + "                            kr 2,34 per stk\n"
          + "                        </p>\n"
          + "                    \n"
          + "\n"
          + "                    <h3 class=\"name\">\n"
          + "                        <div class=\"name-main wrap-two-lines\">Raspberry &amp; Pomegranat-te</div>\n"
          + "                        <div class=\"name-extra wrap-one-line\">\n"
          + "                            \n"
          + "\n"
          + "                            Infuso, 20 stk\n"
          + "                        </div>\n"
          + "                    </h3>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                \n"
          + "                    </a>\n"
          + "                \n"
          + "\n"
          + "                <div class=\"buttons\">\n"
          + "\n"
          + "                    \n"
          + "                        \n"
          + "                            <div class=\"add-to-cart-group\" data-product=\"27410\">\n"
          + "                                <div class=\"not-in-cart\">\n"
          + "                                    <button type=\"button\" class=\" add-to-cart btn btn-sm btn-primary\" data-action=\"add-to-cart\" data-product=\"27410\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Kjøp Raspberry &amp; Pomegranat-te Infuso, 20 stk\" data-tr-location=\"Product Discounts\">\n"
          + "                                        Kjøp\n"
          + "                                    </button>\n"
          + "                                </div>\n"
          + "                                <div class=\"in-cart\">\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-1\" data-action=\"add-to-cart\" data-product=\"27410\" data-quantity=\"-1\" data-to-list=\"cart\" aria-label=\"Fjern 1 Raspberry &amp; Pomegranat-te fra handlekurven\" title=\"Fjern 1 Raspberry &amp; Pomegranat-te fra handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-minus\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Minus-symbol\">\n"
          + "    <rect class=\"fill\" x=\"0\" y=\"19.6\" width=\"45\" height=\"5.8\"></rect>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-3\" data-action=\"add-to-cart\" data-product=\"27410\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Legg til 1 Raspberry &amp; Pomegranat-te i handlekurven\" title=\"Legg til 1 Raspberry &amp; Pomegranat-te i handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-plus\" x=\"0\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Pluss-symbol\">\n"
          + "    <polygon class=\"fill\" points=\"45 19.6 25.4 19.6 25.4 0 19.6 0 19.6 19.6 0 19.6 0 25.4 19.6 25.4 19.6 45 25.4 45 25.4 25.4 45 25.4 \"></polygon>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <div class=\"cart-quantity position-2\" title=\"Antall i handlekurven\">\n"
          + "                                        \n"
          + "                                    </div>\n"
          + "                                </div>\n"
          + "                            </div>\n"
          + "                        \n"
          + "                    \n"
          + "\n"
          + "                </div>\n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                            \n"
          + "                                \n"
          + "\n"
          + "\n"
          + "    <div class=\"col-xs-6 col-sm-3 col-md-2\">\n"
          + "        <div class=\"product-list-item \">\n"
          + "\n"
          + "                \n"
          + "\n"
          + "\n"
          + "                \n"
          + "                \n"
          + "\n"
          + "    \n"
          + "    \n"
          + "\n"
          + "        <div class=\"discount-bubble\">\n"
          + "            <p>\n"
          + "                \n"
          + "\n"
          + "                \n"
          + "                    -30%\n"
          + "                \n"
          + "            </p>\n"
          + "        </div>\n"
          + "\n"
          + "    \n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "                \n"
          + "                    <a data-app-open-native=\"\" href=\"/produkter/27186-twinings-solbaerte/\" class=\"modal-link\">\n"
          + "                \n"
          + "\n"
          + "                    <div>\n"
          + "                        <div class=\"image-container\">\n"
          + "                            \n"
          + "                                <img src=\"https://bilder.kolonial.no/produkter/78622af3-911a-4ae6-b21a-c8eb9d94051d.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=fbc5fd3556f676075f607a56a0109779\" alt=\"Solbærte\" width=\"140\" height=\"140\" title=\"Bilde: © Twinings / Kolonial.no\" srcset=\"https://bilder.kolonial.no/produkter/78622af3-911a-4ae6-b21a-c8eb9d94051d.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=140&amp;w=140&amp;s=fbc5fd3556f676075f607a56a0109779 1x, https://bilder.kolonial.no/produkter/78622af3-911a-4ae6-b21a-c8eb9d94051d.jpeg?fill=solid&amp;fill-color=ffffff&amp;fit=fill&amp;h=280&amp;w=280&amp;s=6b44189c752ae0bfde7aeb93238d3a24 2x\">\n"
          + "                            \n"
          + "\n"
          + "                            \n"
          + "                            \n"
          + "\n"
          + "                            <div class=\"product-classifiers\">\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "\n"
          + "                                \n"
          + "                                    \n"
          + "                                \n"
          + "\n"
          + "                            </div>\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "\n"
          + "                    <p class=\"price label label-price-discounted\">\n"
          + "                        <span class=\"undiscounted-price\">64,40</span> kr 45,08\n"
          + "                    </p>\n"
          + "\n"
          + "                    \n"
          + "                        <p class=\"unit-price\">\n"
          + "                            kr 1,80 per stk\n"
          + "                        </p>\n"
          + "                    \n"
          + "\n"
          + "                    <h3 class=\"name\">\n"
          + "                        <div class=\"name-main wrap-two-lines\">Solbærte</div>\n"
          + "                        <div class=\"name-extra wrap-one-line\">\n"
          + "                            \n"
          + "\n"
          + "                            25 stk\n"
          + "                        </div>\n"
          + "                    </h3>\n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                        \n"
          + "\n"
          + "                    \n"
          + "\n"
          + "                \n"
          + "                    </a>\n"
          + "                \n"
          + "\n"
          + "                <div class=\"buttons\">\n"
          + "\n"
          + "                    \n"
          + "                        \n"
          + "                            <div class=\"add-to-cart-group\" data-product=\"27186\">\n"
          + "                                <div class=\"not-in-cart\">\n"
          + "                                    <button type=\"button\" class=\" add-to-cart btn btn-sm btn-primary\" data-action=\"add-to-cart\" data-product=\"27186\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Kjøp Solbærte 25 stk\" data-tr-location=\"Product Discounts\">\n"
          + "                                        Kjøp\n"
          + "                                    </button>\n"
          + "                                </div>\n"
          + "                                <div class=\"in-cart\">\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-1\" data-action=\"add-to-cart\" data-product=\"27186\" data-quantity=\"-1\" data-to-list=\"cart\" aria-label=\"Fjern 1 Solbærte fra handlekurven\" title=\"Fjern 1 Solbærte fra handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-minus\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Minus-symbol\">\n"
          + "    <rect class=\"fill\" x=\"0\" y=\"19.6\" width=\"45\" height=\"5.8\"></rect>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <button type=\"button\" class=\" cart-quantity-change position-3\" data-action=\"add-to-cart\" data-product=\"27186\" data-quantity=\"1\" data-to-list=\"cart\" aria-label=\"Legg til 1 Solbærte i handlekurven\" title=\"Legg til 1 Solbærte i handlekurven\" data-tr-location=\"Product Discounts\">\n"
          + "                                        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" class=\"icon icon-plus\" x=\"0\" y=\"0\" viewBox=\"0 0 45 45\" enable-background=\"new 0 0 45 45\" xml:space=\"preserve\" aria-label=\"Pluss-symbol\">\n"
          + "    <polygon class=\"fill\" points=\"45 19.6 25.4 19.6 25.4 0 19.6 0 19.6 19.6 0 19.6 0 25.4 19.6 25.4 19.6 45 25.4 45 25.4 25.4 45 25.4 \"></polygon>\n"
          + "</svg>\n"
          + "\n"
          + "                                    </button>\n"
          + "                                    <div class=\"cart-quantity position-2\" title=\"Antall i handlekurven\">\n"
          + "                                        \n"
          + "                                    </div>\n"
          + "                                </div>\n"
          + "                            </div>\n"
          + "                        \n"
          + "                    \n"
          + "\n"
          + "                </div>\n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                            \n"
          + "                        \n"
          + "                    </div>\n"
          + "                </div>\n"
          + "            \n"
          + "\n"
          + "        </div>\n"
          + "    </div>\n"
          + "\n"
          + "\n"
          + "                        </div>\n"
          + "                    </div>\n"
          + "                \n"
          + "            </div>\n"
          + "        </div>";
}
